[main]

# output root folder
outPath = "output"

# number of output files to generate (for random modifications)
numFiles = 10

# apply transformation in series (True) or parallel (False)
chain = true

sr = 44100

transf = ["eq"]

# generate experiment folder with name based on current time
generateExpFolder = true

[analysis]

# analysis window length in seconds
# (not to be confused with the BPF processing window lengths)
window.len = 0.04
# number of hops per analysis window
oversampling = 8

[eq]
window.len = 0.1
window.unit = 's'
std = 5
trunc = 1
BPFtype = 'ramp'
# mel, linear
scale = 'mel'
band.count = 10
min_freq = 0
max_freq = nan
