[main]

# output root folder
outPath = "output"

# number of output files to generate (for random modifications)
numFiles = 10

# apply transformation in series (True) or parallel (False)
chain = true

transf = ["pitch"]

# generate experiment folder with name based on current time
generateExpFolder = true

[analysis]

# analysis window length in seconds
# (not to be confused with the BPF processing window lengths)
window.len = 0.04
# number of hops per analysis window
oversampling = 8

[pitch]
window.len = 0.1
window.unit = 's'
std = 100
trunc = 1
BPFtype = 'ramp'
